### ISSUE TITLE
Поставил новые обновления

### ISSUE THREAD

**Issue by ATAMAH161** [vherasymenk0/hamster-kombat-automator#1]
![Безымянный](https://github.com/vherasymenk0/Hamster-kombat-automator/assets/170763572/aa02e16c-19b1-4d4c-9506-0ee82060ac17)
Так и должен работать софт? как понимаю собирает пассивную награду каждые пару секунд.

**Comment by ATAMAH161** [comment]
Может проблема в настройке Api, Hash, я выбирал android платформу.

**Comment by ATAMAH161** [comment]
Или стоит подождать и софт уже будет дальше карточки прокачивать и прочее?

**Comment by vherasymenk0** [comment]
Так не должно быть, пофиксил, спуль и заново запусти

**Comment by vherasymenk0** [comment]
Работает?

**Comment by ATAMAH161** [comment]
Всё гуд, работает. Спасибо за программу. Хотелось бы узнать вообще по структуре работы, бот прокачивает карточки по максимуму, а потом начинает кликать и так по кругу? И если кликает то прокачивает ли соответствующие бусты для них?

**Comment by vherasymenk0** [comment]
Структура:

Если не авторизирован или устарел токен ---> логин ---> если биржа не выбрана, выбирает биржу ---> проверка доступен ли ежедневный сбор награды за посещение ---> покупка доступних апгрейдов ---> если енергия есть кликает ---> если енергии нет проверяет доступный ли восстановитель енергии, если да актвириует, если нет тогда уходит в ожидание пока не восстановится енергия.

И так по кругу

**Comment by ATAMAH161** [comment]
> Структура:
> 
> Если не авторизирован или устарел токен ---> логин ---> если биржа не выбрана, выбирает биржу ---> проверка доступен ли ежедневный сбор награды за посещение ---> покупка доступних апгрейдов ---> если енергия есть кликает ---> если енергии нет проверяет доступный ли восстановитель енергии, если да актвириует, если нет тогда уходит в ожидание пока не восстановится енергия.
> 
> И так по кругу

И я правильно понимаю софт не собирает награду за пассивный фарм которая капает автоматически если в приложении либо можно забрать при входе в него.

**Comment by vherasymenk0** [comment]
ее не нужно забирать, она автоматически начисляеться

**Comment by ATAMAH161** [comment]
> ее не нужно забирать, она автоматически начисляеться

Есть еще один момент. Что делать если мне нужно перевязать прокси на аккаунте, либо какую-то сессию убрать из работы? Где-то же они все хранятся?

**Comment by vherasymenk0** [comment]
src/data/db.json

**Comment by ATAMAH161** [comment]
> src/data/db.json

![Безымянный](https://github.com/vherasymenk0/hamster-kombat-automator/assets/170763572/164342b0-c5e0-4e71-9f1b-7e948bdafd3f)
![photo1716738797](https://github.com/vherasymenk0/hamster-kombat-automator/assets/170763572/2b81e67d-840f-408a-8c66-cf9173a9914f)

Стали появляться периодически вот такие ошибки, где-то видимо код не правильно начинает работать

**Comment by vherasymenk0** [comment]
1. Это проблема на сервере, из-за того что он перегружен и долго отвечает. Когда сервер даст ответ, тогда все снова заработает. Бот будет делать запрос пока не получит ответ.
2. Пофиксил, спуль
