### ISSUE TITLE
Daily combo not work

### ISSUE THREAD

**Issue by Ziakimbogo** [vherasymenk0/hamster-kombat-automator#13]
Daily combo claim is unavailable: Error: Api | claimCombo() | Error: api_code: DAILY_COMBO_NOT_READY | api_message: DailyComboNotReady combo

can you fix it ?

**Comment by METABYTECODE** [comment]
Слишком запарно фиксить, учитывая что API обновляется ну слишком поздно. Плюс он странно учитывает время комбо. API допустим возвращает, что дата комбо 1 число, а по факту сейчас 2, то бот шлет нахуй это комбо
