### ISSUE TITLE
Баг с покупкой обновлений

### ISSUE THREAD

**Issue by ChernikovM** [vherasymenk0/hamster-kombat-automator#2]
![image](https://github.com/vherasymenk0/hamster-kombat-automator/assets/64634353/a4aae31b-3a23-4c76-bcf0-d23890a4dcf5)
Так как бот ждет 10 минут постоянно чтоб снова попробовать купить айтем он практически ничего не кликает, соотвественно не тратит стамину, а значит не будет юзать буст на стамину, можете пофиксить?

**Comment by vherasymenk0** [comment]
Fixed
