### ISSUE TITLE
Достаточно денег на балансе

### ISSUE THREAD

**Issue by Dxwny** [vherasymenk0/hamster-kombat-automator#4]
`12:43:31 |  WARN   | .ENV | Insufficient balance to improve [licence_south_america] to 13 lvl | Price: 403652 | Balance 405874`
`12:43:31 |  WARN   | .ENV | Sleep 10 minutes`
Денег достаточно, но покупка все равно не совершается

**Comment by vherasymenk0** [comment]
спуль обновления, если снова повториться - отпиши

**Comment by everancii** [comment]
Обновився, зараз бот не засинає

![1234](https://github.com/vherasymenk0/hamster-kombat-automator/assets/25101002/973a8225-87e8-4f9a-b28b-04d45678b313)

**Comment by ATAMAH161** [comment]
![Безымянный](https://github.com/vherasymenk0/hamster-kombat-automator/assets/170763572/56ee96f4-9aa9-4357-9c91-7ee6d58657c4)

Чёт сейчас проблемы с добавлением аккаунта появились, не приходит код

**Comment by vherasymenk0** [comment]
> [everancii](/everancii)

спуль

**Comment by ATAMAH161** [comment]
Кстати сейчас мне кажется бот не логично работает. Он попеременно сначала тапает а потом улучшает карточки, но остается еще больше 2лямов поинтов и соответсвенно карточки есть для покупки, но бот уходит в сон.

**Comment by vherasymenk0** [comment]
Он сначала улучшает карточки, а потом тапает

**Comment by ATAMAH161** [comment]
В чём прикол, то приходит код для нового аккаунта, то нет. Добавляю через +.

**Comment by ATAMAH161** [comment]
![Безымянный](https://github.com/vherasymenk0/hamster-kombat-automator/assets/170763572/aff5d854-9d2c-4340-b2d0-ae8b9afad205)

И Софт кстати почему-то не обрабатывает аккаунты параллельно. Как видно на скрине 1 аккаунт встал в сон, второй тоже ждёт и между пробуждениями успевает скрещивать карточки
