### ISSUE TITLE
Asking a question

### ISSUE THREAD

**Issue by iPurya** [vherasymenk0/hamster-kombat-automator#6]
Hi dear,
can i ask you how did you mitm telegram webapp ?
how can i intercept telegram webapps requests using burpsuite for example ?

**Comment by vherasymenk0** [comment]
Hi, you don't need to catch traffic by mitm or burpsuite to get telegram
web data, it's handle through the telegram api, check out the code of any
of my automators

**Comment by Fushicho373** [comment]
|  ERROR  | 1HAO | Error: Api | login() | Error: Request failed with status code 500，how to solve？bro

**Comment by vherasymenk0** [comment]
All code 5xx errors are server errors. Now hamster servers can't withstand the load and often requests have failed. 
Automator works correctly, the problem is in the hamster servers
