### ISSUE TITLE
Buying multiple upgrades

### ISSUE THREAD

**Issue by niklv** [vherasymenk0/hamster-kombat-automator#7]
After receiving daily combo (3 secret cards, +5kk coins, by manually collect in mini-app)
Bot does not buying multiple upgrades.
After bot restart it purchase only one upgrade (sometimes  two), tap coins and sleep.

Currently account balance is 4kk+ coins.
Logs:
```
14:20:03 |  INFO   | NIKLV | Used cached tg web data | Cache will be revalidated in [22h:26m:18s]
14:20:07 | SUCCESS | NIKLV | Successfully authenticated
14:20:10 |  INFO   | NIKLV | Last passive earn: 12804 | Earn every hour: 357315
14:20:13 | SUCCESS | NIKLV | Upgraded [tokenomics_expert] to 10 lvl | +919 | Total per hour 358234
14:20:13 | SUCCESS | NIKLV | Successfully tapped! (+147) | Balance: 4585428
14:20:23 | SUCCESS | NIKLV | Upgraded [licence_north_america] to 10 lvl | +1765 | Total per hour 359999
14:20:23 |  INFO   | NIKLV | Minimum energy reached: 0 | Approximate energy recovery time 31 minutes
```

**Comment by vherasymenk0** [comment]
The purchase of upgrade logic is implemented in such a way that only the upgrade with the best price-profit ratio is purchased.

**Comment by niklv** [comment]
@vherasymenk0 so if upgrade has best price/earn ratio and cooldown. Bot will wait for this update to be available?
In my above case I can purchase literally every update.

**Comment by vherasymenk0** [comment]
Yes, bot will wait. If u have enough balance bot will buy this upgrade by CD

**Comment by niklv** [comment]
I think there are still a problem. Cause i restart automator it purchase a few things and start sleep. I restart it again and it again purchase a few things and start slip. I will return latet with codereview this part of your automator

**Comment by niklv** [comment]
@vherasymenk0 please reopen

Lets assume that we have a few upgrades with best P/E ratio and we have a lot of coins (for example we solve 1kk chipher). https://github.com/vherasymenk0/hamster-kombat-automator/blob/main/src/automator/automator.ts#L271
We successfully bought upgrade, and then we go to tap section (tap mode is enabled)
For example there are no daily turbo, no taps available and energy boost is not ready.

So we are here:
https://github.com/vherasymenk0/hamster-kombat-automator/blob/main/src/automator/automator.ts#L295

After that we just sleep for next taps avaible. But as i mention above we have a multiple upgrades in pipeline.
